/*
 * The problem is taken from https://projecteuler.net/problem=002
 * Copyright (C) 2021 Maxim Rebguns. Licensed under MIT. See the
 * LICENSE file for details. 
 * 
 * Problem
 * =======
 * Each new term in the Fibonacci sequence is generated by
 * adding the previous two terms. By starting with 1 and 2,
 * the first 10 terms will be:
 *     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose
 * values do not exceed four million, find the sum of the
 * even-valued terms.
 * 
 * Solution
 * ========
 * This solution defines two variables for the two current
 * values in the fibonacci sequence. It also defines a
 * variable for the answer to which even numbers in the
 * sequence are added. The solution iterates until the
 * maximum number is reached. During every iteration,
 * the sum of the two current values is set to the
 * second value, and the previous sum is set to the
 * first value. Finally, if the new sum is divisible by
 * two, then it's added to the cumulative sum. The
 * cumulative sum is then returned.
 */

#include <stdio.h>

/*
 * Get the sum of all even fibonacci numbers that are less
 * than `max`.
 */
unsigned int solution(unsigned int max)
{
    unsigned int value_a = 1;
    unsigned int value_b = 2;
    unsigned int sum     = 2;

    // If max is a small number, then the answer
    // is immediately returned.
    if (max == 0) {
        return 0;
    } else if (max == 1 || max == 2) {
        return 2;
    }

    // Iterate until the max value is reached.
    while (value_a < max && value_b < max) {
        // Here `value_b` becomes the next term in
        // the sequence and `value_a` becomes the
        // previous term.
        value_b = value_a + value_b;
        value_a = value_b - value_a;

        // The value is added to the sum if it's
        // even.
        if (value_b % 2 == 0) {
            sum += value_b;
        }
    }

    return sum;
}

int main(void)
{
    // Get the solution where the max
    // number is 4 million.
    printf("%u\n", solution(4000000));

    return 0;
}
